version: "3.9"

services:
  web:
    build: .
    command: python src/manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - db
    healthcheck:
      test: ["CMD", "python", "src/manage.py", "check"]
      interval: 30s
      timeout: 10s
      retries: 5

  db:
    image: postgres:14-alpine
    environment:
      POSTGRES_DB: secure_atcs
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Optional: Snort IDS (disabled by default). Enable with: docker compose --profile ids up
  snort:
    profiles: ["ids"]
    image: alpine
    command: ["/bin/sh", "-c", "echo 'Snort placeholder' && tail -f /dev/null"]

volumes:
  pgdata:
