# Generated by Django 5.0.7 on 2025-08-31 23:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="anprresult",
            name="image_path",
        ),
        migrations.AddField(
            model_name="anprresult",
            name="detection_method",
            field=models.CharField(default="opencv_real", max_length=50),
        ),
        migrations.AddField(
            model_name="anprresult",
            name="detection_region",
            field=models.JSONField(
                blank=True, help_text="Bounding box coordinates", null=True
            ),
        ),
        migrations.AddField(
            model_name="anprresult",
            name="image_size",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="anprresult",
            name="transaction",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="dashboard.transaction",
            ),
        ),
        migrations.AlterField(
            model_name="anprresult",
            name="confidence",
            field=models.FloatField(
                default=0.0, help_text="Detection confidence (0-1)"
            ),
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("LOGIN", "User Login"),
                            ("LOGOUT", "User Logout"),
                            ("TRANSACTION_CREATE", "Transaction Created"),
                            ("TRANSACTION_UPDATE", "Transaction Updated"),
                            ("PAYMENT_PROCESS", "Payment Processed"),
                            ("ANPR_DETECT", "ANPR Detection"),
                            ("SYSTEM_ERROR", "System Error"),
                        ],
                        max_length=20,
                    ),
                ),
                ("details", models.JSONField(blank=True, null=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True, null=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
    ]
