# Generated by Django 5.0.7 on 2025-09-01 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0002_remove_anprresult_image_path_and_more"),
    ]

    operations = []
