# Generated by Django 5.0.7 on 2025-09-01 01:36

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0003_auto_20250901_0202"),
    ]

    operations = [
        migrations.RenameField(
            model_name="transaction",
            old_name="amount",
            new_name="toll_amount",
        ),
        migrations.RemoveField(
            model_name="transaction",
            name="audit_hash",
        ),
        migrations.RemoveField(
            model_name="transaction",
            name="gate_id",
        ),
        migrations.AddField(
            model_name="transaction",
            name="blockchain_hash",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="transaction",
            name="confidence",
            field=models.FloatField(default=0.5, help_text="OCR confidence level"),
        ),
        migrations.AddField(
            model_name="transaction",
            name="error_message",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="transaction",
            name="location",
            field=models.CharField(default="Main Toll Plaza", max_length=100),
        ),
        migrations.AddField(
            model_name="transaction",
            name="payment_reference",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="transaction",
            name="processed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="transaction",
            name="transaction_id",
            field=models.CharField(default=uuid.uuid4, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="payment_method",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ECOCASH", "EcoCash"),
                    ("ZIPIT", "ZiPiT"),
                    ("VISA", "Visa Card"),
                    ("MASTERCARD", "Mastercard"),
                    ("CASH", "Cash"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("PROCESSING", "Processing"),
                    ("COMPLETED", "Completed"),
                    ("FAILED", "Failed"),
                    ("CANCELLED", "Cancelled"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
    ]
