# Generated by GitHub Copilot on 2025-09-02
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0004_rename_amount_transaction_toll_amount_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlateRegistration",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("license_plate", models.CharField(max_length=20, unique=True)),
                ("normalized_plate", models.CharField(max_length=20, unique=True, db_index=True)),
                ("phone_number", models.CharField(max_length=20)),
                ("owner_name", models.CharField(max_length=100, blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={"ordering": ["-updated_at"]},
        ),
    ]
