# Generated by Django 5.0.7 on 2025-09-02 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0005_plate_registration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plateregistration",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
