# Generated by GitHub Copilot on 2025-09-03
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0005_plate_registration"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="image",
            field=models.ImageField(upload_to='transactions/', blank=True, null=True),
        ),
        migrations.AddField(
            model_name="transaction",
            name="plate_roi",
            field=models.ImageField(upload_to='transactions/roi/', blank=True, null=True),
        ),
    ]
