# Generated by GitHub Copilot on 2025-09-03
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0006_transaction_images"),
    ]

    operations = [
        migrations.AddField(
            model_name="plateregistration",
            name="plate_image",
            field=models.ImageField(upload_to='plates/', blank=True, null=True),
        ),
    ]
