# Generated by Django 5.0.7 on 2025-09-03 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0006_alter_plateregistration_id"),
        ("dashboard", "0007_plateregistration_plate_image"),
    ]

    operations = []
